export const HUNTER_NAME_MAP: Record<string, string> = {
  'Abyss Crawler': 'Shadow Creeper',
  'Abyss Crawler Large': 'Shadow Charger',
  'Abyss Mass': 'Summoned Saviour',
  'Arborium Keeper': 'Memoria',
  'Aspid Collector': 'Aknid',
  'Bell Fly': 'Winged Furm',
  'Bell Goomba': 'Furm',
  'Black Thread Core': 'Void Mass',
  'Blade Spider': 'Pharlid',
  'Blade Spider Hang': 'Pharlid Diver',
  'Bloat Roach': 'Bloatroach',
  'Bloom Puncher': 'Gahlia',
  'Bloom Shooter': 'Pollenica',
  'Blue Assistant': 'Plasmified Zango',
  'Bone Beast': 'Bell Beast',
  'Bone Circler': 'Caranid',
  'Bone Circler Vicious': 'Vicious Caranid',
  'Bone Crawler': 'Kilik',
  'Bone Flyer': 'Beastfly',
  'Bone Flyer Giant': 'Savage Beastfly',
  'Bone Goomba': 'Skull Scuttler',
  'Bone Goomba Bounce Fly': 'Skullwing',
  'Bone Goomba Large': 'Skull Brute',
  'Bone Hopper': 'Hardbone Hopper',
  'Bone Hopper Giant': 'Hardbone Elder',
  'Bone Hunter': 'Skarr Stalker',
  'Bone Hunter Buzzer': 'Skarrwing',
  'Bone Hunter Chief': 'Last Claw',
  'Bone Hunter Child': 'Skarr Scout',
  'Bone Hunter Fly': 'Spear Skarr ',
  'Bone Hunter Throw': 'Skarrgard',
  'Bone Hunter Tiny': 'Skarrlid',
  'Bone Hunter Trapper': 'Gurr the Outcast',
  'Bone Roller': 'Mawling',
  'Bone Spitter': 'Tarmite',
  'Bone Thumper': 'Marrowmaw',
  'Bone Worm': 'Grom',
  'Bone Worm BlueBlood': 'Plasmid',
  'Bone Worm BlueTurret': 'Plasmidas',
  'Centipede Trap': 'Garpid',
  'Citadel Bat': 'Drapefly',
  'Citadel Bat Large': 'Drapelord',
  'Clockwork Dancer': 'Cogwork Dancers',
  'Clover Dancer': 'Clover Dancers',
  'Cloverstag': 'Cloverstag',
  'Cloverstag White': 'Palestag',
  'Conductor Boss': 'The Unravelled',
  'Coral Big Jellyfish': 'Yumama ',
  'Coral Brawler': 'Karak Gor',
  'Coral Bubble Brute': 'Corrcrust Karaka',
  'Coral Conch Driller': 'Conchfly',
  'Coral Conch Driller Giant': 'Great Conchfly',
  'Coral Conch Shooter': 'Driznit',
  'Coral Conch Shooter Heavy': 'Driznarga',
  'Coral Conch Stabber': 'Pokenabbin',
  'Coral Flyer': 'Kakri',
  'Coral Flyer Throw': 'Yago',
  'Coral Goomba Large': 'Crustcrag',
  'Coral Goombas': 'Crustcrawler',
  'Coral Hunter': 'Alita',
  'Coral Judge': 'Judge',
  'Coral Judge Child': 'Squirrm',
  'Coral King': 'Crust King Khann',
  'Coral Spike Goomba': 'Coral Furm',
  'Coral Swimmer Fat': 'Kai',
  'Coral Swimmer Small': 'Yuma',
  'Coral Warrior': 'Karaka',
  'Coral Warrior Grey': 'Watcher at the Edge',
  'Crawfather': 'Crawfather',
  'Crow': 'Craw',
  'Crowman': 'Tallcraw',
  'Crowman Dagger': 'Squatcraw',
  'Crowman Dagger Juror': 'Squatcraw Juror',
  'Crowman Juror': 'Tallcraw Juror',
  'Crowman Juror Tiny': 'Craw Juror',
  'Crypt Worm': 'Gromling',
  'Crystal Drifter': 'Mnemonid',
  'Crystal Drifter Giant': 'Mnemonord',
  'Dock Bomber': 'Flintflame Flyer',
  'Dock Charger': 'Deep Diver',
  'Dock Flyer': 'Flintstone Flyer',
  'Dock Guard Thrower': 'Forebrothers Signis & Gron',
  'Dock Worker': 'Smelt Shoveller',
  'Dragonfly Large': 'Pendragor',
  'Dustroach': 'Muckroach',
  'Dustroach Pollywog': 'Slubberlug',
  'Farmer Catcher': 'Dreg Catcher',
  'Farmer Centipede': 'Thread Raker',
  'Farmer Scissors': 'Silk Snipper',
  'Farmer Wisp': 'Burning Bug',
  'Fields Flock Flyers': 'Brushflit',
  'Fields Flyer': 'Flapping Fertid',
  'Fields Goomba': 'Fertid',
  'First Weaver': 'First Sinner',
  'Flower Drifter': 'Phacia',
  'Flower Queen': 'Nyleth',
  'Garmond': 'Lost Garmond',
  'Garmond_Zaza': 'Garmond & Zaza',
  'Giant Centipede': 'Bell Eater',
  'Giant Flea': 'Huge Flea',
  'Gloom Beast': 'Gargant Gloom',
  'Gloomfly': 'Gloomsac',
  'Gnat Giant': 'Mitemother',
  'Grass Goomba': 'Leaf Roller',
  'Grasshopper Child': 'Kindanir',
  'Grasshopper Fly': 'Escalion',
  'Grasshopper Slasher': 'Verdanir',
  'Hornet Dragonfly': 'Pendra',
  'Hunter Queen': 'Skarrsinger Karmelita',
  'Lace': 'Lace',
  'Last Judge': 'Last Judge',
  'Lifeblood Fly': 'Winged Lifeseed',
  'Lightbearer': 'Lampbearer',
  'Lilypad Fly': 'Leaf Glider',
  'Lilypad Trap': 'Nuphar',
  'Lost Lace': 'Lost Lace',
  'Maggots': 'Muckmaggot',
  'Mite': 'Mite',
  'Mite Heavy': 'Drapemite',
  'Mitefly': 'Fluttermite',
  'MossBone Crawler': 'Mossgrub',
  'MossBone Crawler Fat': 'Massive Mossgrub',
  'MossBone Fly': 'Mossmir',
  'Mossbone Mother': 'Moss Mother',
  'Peaks Drifter': 'Driftlin',
  'Phantom': 'Phantom',
  'Pilgrim 01': 'Pilgrim Pouncer',
  'Pilgrim 01 Song': 'Choir Pouncer',
  'Pilgrim 02': 'Pilgrim Hulk',
  'Pilgrim 02 Song': 'Choir Hornhead',
  'Pilgrim 03': 'Pilgrim Groveller',
  'Pilgrim 03 Song': 'Choir Bellbearer',
  'Pilgrim 03 Understore': 'Underscrub',
  'Pilgrim 04': 'Pilgrim Hornfly',
  'Pilgrim 04 Song': 'Choir Flyer',
  'Pilgrim 05': 'Elder Pilgrim',
  'Pilgrim Bell Thrower': 'Pilgrim Bellbearer',
  'Pilgrim Bellthrower Fly': 'Winged Pilgrim Bellbearer',
  'Pilgrim Fisher': 'Pondcatcher',
  'Pilgrim Fly': 'Winged Pilgrim',
  'Pilgrim Hiker': 'Pilgrim Hiker',
  'Pilgrim Moss Spitter': 'Overgrown Pilgrim',
  'Pilgrim Staff Understore': 'Undersweep',
  'Pilgrim StaffWielder': 'Pilgrim Guide',
  'Pilgrim Stomper Song': 'Choir Elder',
  'Pinstress Boss': 'Pinstress',
  'Poke Swimmer': 'Spinebeak Kai',
  'Pond Skater': 'Pond Skipper',
  'Rhino': 'Rhinogrund',
  'Roachfeeder Short': 'Roachcatcher',
  'Roachfeeder Tall': 'Roachfeeder',
  'Roachkeeper': 'Roachkeeper',
  'Roachkeeper Chef': 'Disgraced Chef Lugoli',
  'Roachkeeper Chef Tiny': 'Roachserver',
  'Rock Roller': 'Flintbeetle',
  'Roof Crab': 'Craggler',
  'Rosary Pilgrim': 'Covetous Pilgrim',
  'Rosary Thief': 'Snitchfly',
  'Sand Centipede': 'Sandcarver',
  'Scholar': 'Vaultkeeper',
  'Scrollkeeper': 'Scrollreader',
  'Seth': 'Shrine Guardian Seth',
  'Shakra': 'Shakra',
  'Shell Fossil Mimic': 'Shardillard',
  'Shellwood Gnat': 'Shellwood Gnat',
  'Shellwood Wasp': 'Wood Wasp',
  'Shield Dock Worker': 'Smokerock Sifter',
  'Silk Boss': 'Grand Mother Silk',
  'Skull King': 'Skull Tyrant',
  'Slab Fly Broodmother': 'Broodmother',
  'Slab Fly Large': 'Wardenfly',
  'Slab Fly Mid': 'Guardfly',
  'Slab Fly Small': 'Scabfly',
  'Slab Fly Small Fresh': 'Freshfly',
  'Slab Prisoner Fly New': 'Puny Penitent',
  'Slab Prisoner Leaper New': 'Penitent',
  'Small Crab': 'Cragglite',
  'Song Administrator': 'Minister',
  'Song Automaton 01': 'Cogwork Choirbug',
  'Song Automaton 02': 'Cogwork Cleanser',
  'Song Automaton Ball': 'Cogwork Clapper',
  'Song Automaton Fly': 'Cogworker',
  'Song Automaton Fly Spike': 'Cogwork Spine',
  'Song Automaton Goomba': 'Cogwork Crawler',
  'Song Automaton Shield': 'Cogwork Defender',
  'Song Creeper': 'Mortician',
  'Song Golem': 'Fourth Chorus',
  'Song Handmaiden': 'Clawmaiden',
  'Song Heavy Sentry': 'Choir Clapper',
  'Song Knight': 'Second Sentinel',
  'Song Pilgrim 01': 'Envoy',
  'Song Pilgrim 02': 'Surgeon',
  'Song Pilgrim 03': 'Choristor',
  'Song Pilgrim Maestro': 'Maestro',
  'Song Reed': 'Reed',
  'Song Reed Grand': 'Grand Reed',
  'Song Scholar Acolyte': 'Vaultborn',
  'Song Threaded Husk': 'Dreg Husk',
  'Song Threaded Husk Spin': 'Dregwheel',
  'Spike Lazy Flyer': 'Imoba',
  'Spike Swimmer': 'Steelspine Kai',
  'Spine Floater': 'Hoker',
  'Spinner Boss': 'Widow',
  'Splinter Queen': 'Sister Splinter',
  'Stick Insect': 'Splinter',
  'Stick Insect Charger': 'Splinterhorn',
  'Stick Insect Flyer': 'Splinterbark',
  'Surface Scuttler': 'Skrill',
  'Swamp Barnacle': 'Barnak',
  'Swamp Drifter': 'Mothleaf Lagnia',
  'Swamp Ductsucker': 'Ductsucker',
  'Swamp Goomba': 'Miremite',
  'Swamp Mosquito': 'Swamp Squit',
  'Swamp Mosquito Skinny': 'Spit Squit',
  'Swamp Muckman': 'Stilkin',
  'Swamp Muckman Tall': 'Stilkin Trapper',
  'Swamp Shaman': 'Groal the Great',
  'Tar Slug': 'Lavalug',
  'Tar Slug Huge': 'Lavalarga',
  'Tormented Trobbio': 'Tormented Trobbio',
  'Trobbio': 'Trobbio',
  'Understore Automaton': 'Cogwork Underfly',
  'Understore Automaton EX': 'Cogwork Hauler',
  'Understore Heavy': 'Undercrank',
  'Understore Mite Giant': 'Giant Drapemite',
  'Understore Poker': 'Underpoke',
  'Understore Small': 'Underworker',
  'Understore Thrower': 'Underloft',
  'Vampire Gnat': 'Moorwing',
  'Void Tendrils': 'Void Tendrils',
  'Weaver Servitor': 'Servitor Ignim',
  'Weaver Servitor Large': 'Servitor Boran',
  'White Palace Fly': 'Wingmould',
  'Wisp': 'Wisp',
  'Wisp Pyre Effigy': 'Father of the Flame',
  'Wraith': 'Wraith',
  'Zap Core Enemy': 'Voltvyrm',
}

export const HUNTER_DEFAULT_TARGET = 10

export const HUNTER_JOURNAL_TARGETS: Record<string, number> = {
  'Abyss Crawler': 16,
  'Abyss Crawler Large': 6,
  'Abyss Mass': 1,
  'Arborium Keeper': 2,
  'Aspid Collector': 15,
  'Bell Fly': 12,
  'Bell Goomba': 25,
  'Black Thread Core': 8,
  'Blade Spider': 20,
  'Blade Spider Hang': 10,
  'Bloat Roach': 12,
  'Bloom Puncher': 20,
  'Bloom Shooter': 10,
  'Blue Assistant': 1,
  'Bone Beast': 1,
  'Bone Circler': 25,
  'Bone Circler Vicious': 15,
  'Bone Crawler': 25,
  'Bone Flyer': 30,
  'Bone Flyer Giant': 2,
  'Bone Goomba': 35,
  'Bone Goomba Bounce Fly': 15,
  'Bone Goomba Large': 15,
  'Bone Hopper': 20,
  'Bone Hopper Giant': 10,
  'Bone Hunter': 15,
  'Bone Hunter Buzzer': 30,
  'Bone Hunter Chief': 6,
  'Bone Hunter Child': 20,
  'Bone Hunter Fly': 10,
  'Bone Hunter Throw': 2,
  'Bone Hunter Tiny': 25,
  'Bone Hunter Trapper': 1,
  'Bone Roller': 30,
  'Bone Spitter': 10,
  'Bone Thumper': 8,
  'Bone Worm': 10,
  'Bone Worm BlueBlood': 15,
  'Bone Worm BlueTurret': 6,
  'Centipede Trap': 30,
  'Citadel Bat': 30,
  'Citadel Bat Large': 4,
  'Clockwork Dancer': 1,
  'Clover Dancer': 1,
  'Cloverstag': 10,
  'Cloverstag White': 1,
  'Conductor Boss': 1,
  'Coral Big Jellyfish': 3,
  'Coral Brawler': 8,
  'Coral Bubble Brute': 6,
  'Coral Conch Driller': 8,
  'Coral Conch Driller Giant': 2,
  'Coral Conch Shooter': 25,
  'Coral Conch Shooter Heavy': 14,
  'Coral Conch Stabber': 16,
  'Coral Flyer': 10,
  'Coral Flyer Throw': 12,
  'Coral Goomba Large': 6,
  'Coral Goombas': 10,
  'Coral Hunter': 6,
  'Coral Judge': 15,
  'Coral Judge Child': 4,
  'Coral King': 1,
  'Coral Spike Goomba': 15,
  'Coral Swimmer Fat': 10,
  'Coral Swimmer Small': 16,
  'Coral Warrior': 10,
  'Coral Warrior Grey': 1,
  'Crawfather': 1,
  'Crow': 25,
  'Crowman': 20,
  'Crowman Dagger': 15,
  'Crowman Dagger Juror': 8,
  'Crowman Juror': 10,
  'Crowman Juror Tiny': 15,
  'Crypt Worm': 25,
  'Crystal Drifter': 10,
  'Crystal Drifter Giant': 3,
  'Dock Bomber': 10,
  'Dock Charger': 5,
  'Dock Flyer': 25,
  'Dock Guard Thrower': 1,
  'Dock Worker': 25,
  'Dragonfly Large': 10,
  'Dustroach': 20,
  'Dustroach Pollywog': 12,
  'Farmer Catcher': 20,
  'Farmer Centipede': 15,
  'Farmer Scissors': 25,
  'Farmer Wisp': 8,
  'Fields Flock Flyers': 15,
  'Fields Flyer': 20,
  'Fields Goomba': 25,
  'First Weaver': 1,
  'Flower Drifter': 25,
  'Flower Queen': 1,
  'Garmond': 1,
  'Garmond_Zaza': 1,
  'Giant Centipede': 1,
  'Giant Flea': 1,
  'Gloom Beast': 4,
  'Gloomfly': 15,
  'Gnat Giant': 10,
  'Grass Goomba': 10,
  'Grasshopper Child': 10,
  'Grasshopper Fly': 10,
  'Grasshopper Slasher': 10,
  'Hornet Dragonfly': 10,
  'Hunter Queen': 1,
  'Lace': 2,
  'Last Judge': 1,
  'Lifeblood Fly': 8,
  'Lightbearer': 20,
  'Lilypad Fly': 12,
  'Lilypad Trap': 6,
  'Lost Lace': 1,
  'Maggots': 80,
  'Mite': 30,
  'Mite Heavy': 20,
  'Mitefly': 25,
  'MossBone Crawler': 25,
  'MossBone Crawler Fat': 3,
  'MossBone Fly': 20,
  'Mossbone Mother': 3,
  'Peaks Drifter': 20,
  'Phantom': 1,
  'Pilgrim 01': 35,
  'Pilgrim 01 Song': 30,
  'Pilgrim 02': 10,
  'Pilgrim 02 Song': 15,
  'Pilgrim 03': 35,
  'Pilgrim 03 Song': 25,
  'Pilgrim 03 Understore': 20,
  'Pilgrim 04': 15,
  'Pilgrim 04 Song': 20,
  'Pilgrim 05': 5,
  'Pilgrim Bell Thrower': 10,
  'Pilgrim Bellthrower Fly': 10,
  'Pilgrim Fisher': 20,
  'Pilgrim Fly': 25,
  'Pilgrim Hiker': 10,
  'Pilgrim Moss Spitter': 20,
  'Pilgrim Staff Understore': 10,
  'Pilgrim StaffWielder': 15,
  'Pilgrim Stomper Song': 6,
  'Pinstress Boss': 1,
  'Poke Swimmer': 10,
  'Pond Skater': 15,
  'Rhino': 2,
  'Roachfeeder Short': 20,
  'Roachfeeder Tall': 20,
  'Roachkeeper': 10,
  'Roachkeeper Chef': 1,
  'Roachkeeper Chef Tiny': 10,
  'Rock Roller': 3,
  'Roof Crab': 1,
  'Rosary Pilgrim': 2,
  'Rosary Thief': 4,
  'Sand Centipede': 40,
  'Scholar': 10,
  'Scrollkeeper': 15,
  'Seth': 1,
  'Shakra': 1,
  'Shell Fossil Mimic': 3,
  'Shellwood Gnat': 15,
  'Shellwood Wasp': 12,
  'Shield Dock Worker': 10,
  'Silk Boss': 1,
  'Skull King': 1,
  'Slab Fly Broodmother': 1,
  'Slab Fly Large': 8,
  'Slab Fly Mid': 10,
  'Slab Fly Small': 15,
  'Slab Fly Small Fresh': 20,
  'Slab Prisoner Fly New': 6,
  'Slab Prisoner Leaper New': 8,
  'Small Crab': 3,
  'Song Administrator': 15,
  'Song Automaton 01': 20,
  'Song Automaton 02': 12,
  'Song Automaton Ball': 1,
  'Song Automaton Fly': 15,
  'Song Automaton Fly Spike': 10,
  'Song Automaton Goomba': 15,
  'Song Automaton Shield': 8,
  'Song Creeper': 10,
  'Song Golem': 1,
  'Song Handmaiden': 10,
  'Song Heavy Sentry': 3,
  'Song Knight': 1,
  'Song Pilgrim 01': 20,
  'Song Pilgrim 02': 3,
  'Song Pilgrim 03': 25,
  'Song Pilgrim Maestro': 6,
  'Song Reed': 30,
  'Song Reed Grand': 12,
  'Song Scholar Acolyte': 20,
  'Song Threaded Husk': 8,
  'Song Threaded Husk Spin': 8,
  'Spike Lazy Flyer': 4,
  'Spike Swimmer': 15,
  'Spine Floater': 15,
  'Spinner Boss': 1,
  'Splinter Queen': 1,
  'Stick Insect': 12,
  'Stick Insect Charger': 10,
  'Stick Insect Flyer': 10,
  'Surface Scuttler': 10,
  'Swamp Barnacle': 8,
  'Swamp Drifter': 25,
  'Swamp Ductsucker': 6,
  'Swamp Goomba': 20,
  'Swamp Mosquito': 30,
  'Swamp Mosquito Skinny': 20,
  'Swamp Muckman': 15,
  'Swamp Muckman Tall': 12,
  'Swamp Shaman': 1,
  'Tar Slug': 12,
  'Tar Slug Huge': 8,
  'Tormented Trobbio': 1,
  'Trobbio': 1,
  'Understore Automaton': 25,
  'Understore Automaton EX': 12,
  'Understore Heavy': 4,
  'Understore Mite Giant': 6,
  'Understore Poker': 25,
  'Understore Small': 15,
  'Understore Thrower': 25,
  'Vampire Gnat': 1,
  'Void Tendrils': 1,
  'Weaver Servitor': 8,
  'Weaver Servitor Large': 5,
  'White Palace Fly': 10,
  'Wisp': 15,
  'Wisp Pyre Effigy': 1,
  'Wraith': 10,
  'Zap Core Enemy': 1,
}
