export const HUNTER_ORDER = [
  'MossBone Crawler',
  'MossBone Crawler Fat', 
  'MossBone Fly',
  'Mossbone Mother',
  'Aspid Collector',
  'Bone Goomba',
  'Bone Goomba Bounce Fly',
  'Bone Goomba Large',
  'Skull King',
  'Bone Crawler',
  'Bone Flyer',
  'Bone Flyer Giant',
  'Bone Circler',
  'Bone Circler Vicious',
  'Bone Hopper',
  'Bone Hopper Giant',
  'Bone Spitter',
  'Bone Roller',
  'Bone Thumper',
  'Spine Floater',
  'Rock Roller',
  'Rhino',
  'Crypt Worm',
  'Bone Worm',
  'Bone Beast',
  'Pilgrim 03',
  'Pilgrim 01',
  'Pilgrim 04',
  'Pilgrim 02',
  'Pilgrim Bell Thrower',
  'Pilgrim Fly',
  'Pilgrim 05',
  'Pilgrim Bellthrower Fly',
  'Pilgrim Hiker',
  'Pilgrim StaffWielder',
  'Pilgrim Moss Spitter',
  'Rosary Pilgrim',
  'Rosary Thief',
  'Tar Slug',
  'Tar Slug Huge',
  'Dock Worker',
  'Dock Flyer',
  'Dock Bomber',
  'Shield Dock Worker',
  'Dock Charger',
  'Dock Guard Thrower',
  'Small Crab',
  'Roof Crab',
  'Fields Flock Flyers',
  'Fields Goomba',
  'Fields Flyer',
  'Song Golem',
  'Bone Hunter Tiny',
  'Bone Hunter Buzzer',
  'Bone Hunter Child',
  'Bone Hunter',
  'Bone Hunter Fly',
  'Bone Hunter Throw',
  'Bone Hunter Trapper',
  'Bone Hunter Chief',
  'Hunter Queen',
  'Mite',
  'Mitefly',
  'Gnat Giant',
  'Farmer Catcher',
  'Farmer Scissors',
  'Farmer Centipede',
  'Vampire Gnat',
  'Wisp',
  'Farmer Wisp',
  'Wisp Pyre Effigy',
  'Crow',
  'Crowman',
  'Crowman Dagger',
  'Crowman Juror Tiny',
  'Crowman Juror',
  'Crowman Dagger Juror',
  'Crawfather',
  'Maggots',
  'Dustroach Pollywog',
  'Dustroach',
  'Bloat Roach',
  'Roachfeeder Short',
  'Roachfeeder Tall',
  'Roachkeeper',
  'Roachkeeper Chef Tiny',
  'Roachkeeper Chef',
  'Wraith',
  'Swamp Drifter',
  'Swamp Goomba',
  'Swamp Mosquito',
  'Swamp Mosquito Skinny',
  'Swamp Muckman',
  'Swamp Muckman Tall',
  'Swamp Shaman',
  'Swamp Barnacle',
  'Swamp Ductsucker',
  'Pond Skater',
  'Pilgrim Fisher',
  'Shellwood Gnat',
  'Shellwood Wasp',
  'Stick Insect',
  'Stick Insect Charger',
  'Stick Insect Flyer',
  'Splinter Queen',
  'Flower Drifter',
  'Bloom Shooter',
  'Bloom Puncher',
  'Seth',
  'Flower Queen',
  'Bell Goomba',
  'Bell Fly',
  'Blade Spider',
  'Blade Spider Hang',
  'Shell Fossil Mimic',
  'Sand Centipede',
  'Coral Judge Child',
  'Coral Judge',
  'Last Judge',
  'Coral Spike Goomba',
  'Coral Conch Shooter',
  'Coral Conch Shooter Heavy',
  'Coral Conch Stabber',
  'Coral Conch Driller',
  'Coral Conch Driller Giant',
  'Coral Goombas',
  'Coral Goomba Large',
  'Coral Swimmer Fat',
  'Poke Swimmer',
  'Spike Swimmer',
  'Coral Swimmer Small',
  'Coral Big Jellyfish',
  'Coral Warrior',
  'Coral Flyer',
  'Coral Flyer Throw',
  'Coral Brawler',
  'Coral Hunter',
  'Coral Bubble Brute',
  'Coral King',
  'Coral Warrior Grey',
  'Zap Core Enemy',
  'Citadel Bat',
  'Citadel Bat Large',
  'Mite Heavy',
  'Understore Mite Giant',
  'Understore Small',
  'Pilgrim 03 Understore',
  'Pilgrim Staff Understore',
  'Understore Poker',
  'Understore Thrower',
  'Understore Heavy',
  'Song Pilgrim 01',
  'Pilgrim 01 Song',
  'Pilgrim 02 Song',
  'Pilgrim 03 Song',
  'Pilgrim 04 Song',
  'Pilgrim Stomper Song',
  'Song Pilgrim 03',
  'Song Reed',
  'Song Reed Grand',
  'Song Heavy Sentry',
  'Song Handmaiden',
  'Arborium Keeper',
  'Song Administrator',
  'Song Pilgrim Maestro',
  'Song Knight',
  'Song Threaded Husk',
  'Song Threaded Husk Spin',
  'Song Pilgrim 02',
  'Song Creeper',
  'Conductor Boss',
  'Understore Automaton',
  'Understore Automaton EX',
  'Song Automaton Goomba',
  'Song Automaton Fly',
  'Song Automaton Fly Spike',
  'Song Automaton 01',
  'Song Automaton 02',
  'Song Automaton Shield',
  'Song Automaton Ball',
  'Clockwork Dancer',
  'Song Scholar Acolyte',
  'Lightbearer',
  'Scrollkeeper',
  'Scholar',
  'Trobbio',
  'Tormented Trobbio',
  'Slab Prisoner Leaper New',
  'Slab Prisoner Fly New',
  'Slab Fly Small Fresh',
  'Slab Fly Small',
  'Slab Fly Mid',
  'Slab Fly Large',
  'Slab Fly Broodmother',
  'Peaks Drifter',
  'Crystal Drifter',
  'Crystal Drifter Giant',
  'Weaver Servitor',
  'Weaver Servitor Large',
  'Lifeblood Fly',
  'Bone Worm BlueBlood',
  'Bone Worm BlueTurret',
  'Blue Assistant',
  'Lilypad Fly',
  'Grass Goomba',
  'Hornet Dragonfly',
  'Dragonfly Large',
  'Lilypad Trap',
  'Cloverstag',
  'Cloverstag White',
  'Grasshopper Child',
  'Grasshopper Slasher',
  'Grasshopper Fly',
  'Clover Dancer',
  'Abyss Crawler',
  'Abyss Crawler Large',
  'Gloomfly',
  'Gloom Beast',
  'Void Tendrils',
  'Black Thread Core',
  'Abyss Mass',
  'White Palace Fly',
  'Centipede Trap',
  'Spike Lazy Flyer',
  'Surface Scuttler',
  'Giant Centipede',
  'Giant Flea',
  'Shakra',
  'Garmond_Zaza',
  'Garmond',
  'Pinstress Boss',
  'Spinner Boss',
  'First Weaver',
  'Phantom',
  'Lace',
  'Silk Boss',
  'Lost Lace'
]

export function getHunterOrder(enemyName: string): number {
  const index = HUNTER_ORDER.indexOf(enemyName)
  return index === -1 ? 999 : index
}