export const HUNTER_NAME_MAP: Record<string, string> = {
  'Abyss Crawler': 'Shadow Creeper',
  'Abyss Crawler Large': 'Shadow Charger',
  'Abyss Mass': 'Summoned Saviour',
  'Arborium Keeper': 'Memoria',
  'Aspid Collector': 'Aknid',
  'Bell Fly': 'Winged Furm',
  'Bell Goomba': 'Furm',
  'Black Thread Core': 'Void Mass',
  'Blade Spider': 'Pharlid',
  'Blade Spider Hang': 'Pharlid Diver',
  'Bloat Roach': 'Bloatroach',
  'Bloom Puncher': 'Gahlia',
  'Bloom Shooter': 'Pollenica',
  'Blue Assistant': 'Plasmified Zango',
  'Bone Beast': 'Bell Beast',
  'Bone Circler': 'Caranid',
  'Bone Circler Vicious': 'Vicious Caranid',
  'Bone Crawler': 'Kilik',
  'Bone Flyer': 'Beastfly',
  'Bone Flyer Giant': 'Savage Beastfly',
  'Bone Goomba': 'Skull Scuttler',
  'Bone Goomba Bounce Fly': 'Skullwing',
  'Bone Goomba Large': 'Skull Brute',
  'Bone Hopper': 'Hardbone Hopper',
  'Bone Hopper Giant': 'Hardbone Elder',
  'Bone Hunter': 'Skarr Stalker',
  'Bone Hunter Buzzer': 'Skarrwing',
  'Bone Hunter Chief': 'Last Claw',
  'Bone Hunter Child': 'Skarr Scout',
  'Bone Hunter Fly': 'Spear Skarr ',
  'Bone Hunter Throw': 'Skarrgard',
  'Bone Hunter Tiny': 'Skarrlid',
  'Bone Hunter Trapper': 'Gurr the Outcast',
  'Bone Roller': 'Mawling',
  'Bone Spitter': 'Tarmite',
  'Bone Thumper': 'Marrowmaw',
  'Bone Worm': 'Grom',
  'Bone Worm BlueBlood': 'Plasmid',
  'Bone Worm BlueTurret': 'Plasmidas',
  'Centipede Trap': 'Garpid',
  'Citadel Bat': 'Drapefly',
  'Citadel Bat Large': 'Drapelord',
  'Clockwork Dancer': 'Cogwork Dancers',
  'Clover Dancer': 'Clover Dancers',
  'Cloverstag': 'Cloverstag',
  'Cloverstag White': 'Palestag',
  'Conductor Boss': 'The Unravelled',
  'Coral Big Jellyfish': 'Yumama ',
  'Coral Brawler': 'Karak Gor',
  'Coral Bubble Brute': 'Corrcrust Karaka',
  'Coral Conch Driller': 'Conchfly',
  'Coral Conch Driller Giant': 'Great Conchfly',
  'Coral Conch Shooter': 'Driznit',
  'Coral Conch Shooter Heavy': 'Driznarga',
  'Coral Conch Stabber': 'Pokenabbin',
  'Coral Flyer': 'Kakri',
  'Coral Flyer Throw': 'Yago',
  'Coral Goomba Large': 'Crustcrag',
  'Coral Goombas': 'Crustcrawler',
  'Coral Hunter': 'Alita',
  'Coral Judge': 'Judge',
  'Coral Judge Child': 'Squirrm',
  'Coral King': 'Crust King Khann',
  'Coral Spike Goomba': 'Coral Furm',
  'Coral Swimmer Fat': 'Kai',
  'Coral Swimmer Small': 'Yuma',
  'Coral Warrior': 'Karaka',
  'Coral Warrior Grey': 'Watcher at the Edge',
  'Crawfather': 'Crawfather',
  'Crow': 'Craw',
  'Crowman': 'Tallcraw',
  'Crowman Dagger': 'Squatcraw',
  'Crowman Dagger Juror': 'Squatcraw Juror',
  'Crowman Juror': 'Tallcraw Juror',
  'Crowman Juror Tiny': 'Craw Juror',
  'Crypt Worm': 'Gromling',
  'Crystal Drifter': 'Mnemonid',
  'Crystal Drifter Giant': 'Mnemonord',
  'Dock Bomber': 'Flintflame Flyer',
  'Dock Charger': 'Deep Diver',
  'Dock Flyer': 'Flintstone Flyer',
  'Dock Guard Thrower': 'Forebrothers Signis & Gron',
  'Dock Worker': 'Smelt Shoveller',
  'Dragonfly Large': 'Pendragor',
  'Dustroach': 'Muckroach',
  'Dustroach Pollywog': 'Slubberlug',
  'Farmer Catcher': 'Dreg Catcher',
  'Farmer Centipede': 'Thread Raker',
  'Farmer Scissors': 'Silk Snipper',
  'Farmer Wisp': 'Burning Bug',
  'Fields Flock Flyers': 'Brushflit',
  'Fields Flyer': 'Flapping Fertid',
  'Fields Goomba': 'Fertid',
  'First Weaver': 'First Sinner',
  'Flower Drifter': 'Phacia',
  'Flower Queen': 'Nyleth',
  'Garmond': 'Lost Garmond',
  'Garmond_Zaza': 'Garmond & Zaza',
  'Giant Centipede': 'Bell Eater',
  'Giant Flea': 'Huge Flea',
  'Gloom Beast': 'Gargant Gloom',
  'Gloomfly': 'Gloomsac',
  'Gnat Giant': 'Mitemother',
  'Grass Goomba': 'Leaf Roller',
  'Grasshopper Child': 'Kindanir',
  'Grasshopper Fly': 'Escalion',
  'Grasshopper Slasher': 'Verdanir',
  'Hornet Dragonfly': 'Pendra',
  'Hunter Queen': 'Skarrsinger Karmelita',
  'Lace': 'Lace',
  'Last Judge': 'Last Judge',
  'Lifeblood Fly': 'Winged Lifeseed',
  'Lightbearer': 'Lampbearer',
  'Lilypad Fly': 'Leaf Glider',
  'Lilypad Trap': 'Nuphar',
  'Lost Lace': 'Lost Lace',
  'Maggots': 'Muckmaggot',
  'Mite': 'Mite',
  'Mite Heavy': 'Drapemite',
  'Mitefly': 'Fluttermite',
  'MossBone Crawler': 'Mossgrub',
  'MossBone Crawler Fat': 'Massive Mossgrub',
  'MossBone Fly': 'Mossmir',
  'Mossbone Mother': 'Moss Mother',
  'Peaks Drifter': 'Driftlin',
  'Phantom': 'Phantom',
  'Pilgrim 01': 'Pilgrim Pouncer',
  'Pilgrim 01 Song': 'Choir Pouncer',
  'Pilgrim 02': 'Pilgrim Hulk',
  'Pilgrim 02 Song': 'Choir Hornhead',
  'Pilgrim 03': 'Pilgrim Groveller',
  'Pilgrim 03 Song': 'Choir Bellbearer',
  'Pilgrim 03 Understore': 'Underscrub',
  'Pilgrim 04': 'Pilgrim Hornfly',
  'Pilgrim 04 Song': 'Choir Flyer',
  'Pilgrim 05': 'Elder Pilgrim',
  'Pilgrim Bell Thrower': 'Pilgrim Bellbearer',
  'Pilgrim Bellthrower Fly': 'Winged Pilgrim Bellbearer',
  'Pilgrim Fisher': 'Pondcatcher',
  'Pilgrim Fly': 'Winged Pilgrim',
  'Pilgrim Hiker': 'Pilgrim Hiker',
  'Pilgrim Moss Spitter': 'Overgrown Pilgrim',
  'Pilgrim Staff Understore': 'Undersweep',
  'Pilgrim StaffWielder': 'Pilgrim Guide',
  'Pilgrim Stomper Song': 'Choir Elder',
  'Pinstress Boss': 'Pinstress',
  'Poke Swimmer': 'Spinebeak Kai',
  'Pond Skater': 'Pond Skipper',
  'Rhino': 'Rhinogrund',
  'Roachfeeder Short': 'Roachcatcher',
  'Roachfeeder Tall': 'Roachfeeder',
  'Roachkeeper': 'Roachkeeper',
  'Roachkeeper Chef': 'Disgraced Chef Lugoli',
  'Roachkeeper Chef Tiny': 'Roachserver',
  'Rock Roller': 'Flintbeetle',
  'Roof Crab': 'Craggler',
  'Rosary Pilgrim': 'Covetous Pilgrim',
  'Rosary Thief': 'Snitchfly',
  'Sand Centipede': 'Sandcarver',
  'Scholar': 'Vaultkeeper',
  'Scrollkeeper': 'Scrollreader',
  'Seth': 'Shrine Guardian Seth',
  'Shakra': 'Shakra',
  'Shell Fossil Mimic': 'Shardillard',
  'Shellwood Gnat': 'Shellwood Gnat',
  'Shellwood Wasp': 'Wood Wasp',
  'Shield Dock Worker': 'Smokerock Sifter',
  'Silk Boss': 'Grand Mother Silk',
  'Skull King': 'Skull Tyrant',
  'Slab Fly Broodmother': 'Broodmother',
  'Slab Fly Large': 'Wardenfly',
  'Slab Fly Mid': 'Guardfly',
  'Slab Fly Small': 'Scabfly',
  'Slab Fly Small Fresh': 'Freshfly',
  'Slab Prisoner Fly New': 'Puny Penitent',
  'Slab Prisoner Leaper New': 'Penitent',
  'Small Crab': 'Cragglite',
  'Song Administrator': 'Minister',
  'Song Automaton 01': 'Cogwork Choirbug',
  'Song Automaton 02': 'Cogwork Cleanser',
  'Song Automaton Ball': 'Cogwork Clapper',
  'Song Automaton Fly': 'Cogworker',
  'Song Automaton Fly Spike': 'Cogwork Spine',
  'Song Automaton Goomba': 'Cogwork Crawler',
  'Song Automaton Shield': 'Cogwork Defender',
  'Song Creeper': 'Mortician',
  'Song Golem': 'Fourth Chorus',
  'Song Handmaiden': 'Clawmaiden',
  'Song Heavy Sentry': 'Choir Clapper',
  'Song Knight': 'Second Sentinel',
  'Song Pilgrim 01': 'Envoy',
  'Song Pilgrim 02': 'Surgeon',
  'Song Pilgrim 03': 'Choristor',
  'Song Pilgrim Maestro': 'Maestro',
  'Song Reed': 'Reed',
  'Song Reed Grand': 'Grand Reed',
  'Song Scholar Acolyte': 'Vaultborn',
  'Song Threaded Husk': 'Dreg Husk',
  'Song Threaded Husk Spin': 'Dregwheel',
  'Spike Lazy Flyer': 'Imoba',
  'Spike Swimmer': 'Steelspine Kai',
  'Spine Floater': 'Hoker',
  'Spinner Boss': 'Widow',
  'Splinter Queen': 'Sister Splinter',
  'Stick Insect': 'Splinter',
  'Stick Insect Charger': 'Splinterhorn',
  'Stick Insect Flyer': 'Splinterbark',
  'Surface Scuttler': 'Skrill',
  'Swamp Barnacle': 'Barnak',
  'Swamp Drifter': 'Mothleaf Lagnia',
  'Swamp Ductsucker': 'Ductsucker',
  'Swamp Goomba': 'Miremite',
  'Swamp Mosquito': 'Swamp Squit',
  'Swamp Mosquito Skinny': 'Spit Squit',
  'Swamp Muckman': 'Stilkin',
  'Swamp Muckman Tall': 'Stilkin Trapper',
  'Swamp Shaman': 'Groal the Great',
  'Tar Slug': 'Lavalug',
  'Tar Slug Huge': 'Lavalarga',
  'Tormented Trobbio': 'Tormented Trobbio',
  'Trobbio': 'Trobbio',
  'Understore Automaton': 'Cogwork Underfly',
  'Understore Automaton EX': 'Cogwork Hauler',
  'Understore Heavy': 'Undercrank',
  'Understore Mite Giant': 'Giant Drapemite',
  'Understore Poker': 'Underpoke',
  'Understore Small': 'Underworker',
  'Understore Thrower': 'Underloft',
  'Vampire Gnat': 'Moorwing',
  'Void Tendrils': 'Void Tendrils',
  'Weaver Servitor': 'Servitor Ignim',
  'Weaver Servitor Large': 'Servitor Boran',
  'White Palace Fly': 'Wingmould',
  'Wisp': 'Wisp',
  'Wisp Pyre Effigy': 'Father of the Flame',
  'Wraith': 'Wraith',
  'Zap Core Enemy': 'Voltvyrm',
}

export const HUNTER_DEFAULT_TARGET = 10

export const HUNTER_MAP_LINKS: Record<string, string> = {
  'Abyss Crawler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480134',
  'Abyss Crawler Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480135',
  'Abyss Mass': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480310',
  'Arborium Keeper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480239',
  'Aspid Collector': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479579',
  'Bell Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478195',
  'Bell Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478194',
  'Black Thread Core': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480136',
  'Blade Spider': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478196',
  'Blade Spider Hang': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478197',
  'Bloat Roach': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478263',
  'Bloom Puncher': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478170',
  'Bloom Shooter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478171',
  'Blue Assistant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480347',
  'Bone Beast': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480311',
  'Bone Circler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479080',
  'Bone Circler Vicious': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479081',
  'Bone Crawler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479077',
  'Bone Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479082',
  'Bone Flyer Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480253',
  'Bone Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479079',
  'Bone Goomba Bounce Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479083',
  'Bone Goomba Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480254',
  'Bone Hopper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479555',
  'Bone Hopper Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480255',
  'Bone Hunter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479556',
  'Bone Hunter Buzzer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479558',
  'Bone Hunter Chief': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480312',
  'Bone Hunter Child': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479557',
  'Bone Hunter Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479559',
  'Bone Hunter Throw': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480256',
  'Bone Hunter Tiny': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479563',
  'Bone Hunter Trapper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480314',
  'Bone Roller': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479564',
  'Bone Spitter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479575',
  'Bone Thumper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479576',
  'Bone Worm': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479084',
  'Bone Worm BlueBlood': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479085',
  'Bone Worm BlueTurret': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479086',
  'Centipede Trap': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478981',
  'Citadel Bat': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479002',
  'Citadel Bat Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479003',
  'Clockwork Dancer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480320',
  'Clover Dancer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480322',
  'Cloverstag': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480221',
  'Cloverstag White': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480224',
  'Conductor Boss': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480340',
  'Coral Big Jellyfish': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480225',
  'Coral Brawler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480226',
  'Coral Bubble Brute': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480227',
  'Coral Conch Driller': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480228',
  'Coral Conch Driller Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480229',
  'Coral Conch Shooter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480230',
  'Coral Conch Shooter Heavy': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480231',
  'Coral Conch Stabber': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480232',
  'Coral Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480233',
  'Coral Flyer Throw': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480240',
  'Coral Goomba Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480241',
  'Coral Goombas': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480242',
  'Coral Hunter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480243',
  'Coral Judge': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479084',
  'Coral Judge Child': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480244',
  'Coral King': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480316',
  'Coral Spike Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480245',
  'Coral Swimmer Fat': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480246',
  'Coral Swimmer Small': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480247',
  'Coral Warrior': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480248',
  'Coral Warrior Grey': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480326',
  'Crawfather': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480319',
  'Crow': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479679',
  'Crowman': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479680',
  'Crowman Dagger': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479682',
  'Crowman Dagger Juror': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480487',
  'Crowman Juror': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480486',
  'Crowman Juror Tiny': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480485',
  'Crypt Worm': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479078',
  'Crystal Drifter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479043',
  'Crystal Drifter Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480198',
  'Dock Bomber': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479566',
  'Dock Charger': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480237',
  'Dock Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479554',
  'Dock Guard Thrower': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480317',
  'Dock Worker': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479553',
  'Dragonfly Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480481',
  'Dustroach': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478264',
  'Dustroach Pollywog': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478965',
  'Farmer Catcher': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479685',
  'Farmer Centipede': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478979',
  'Farmer Scissors': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478150',
  'Farmer Wisp': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480440',
  'Fields Flock Flyers': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479560',
  'Fields Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479562',
  'Fields Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479561',
  'First Weaver': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480339',
  'Flower Drifter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478168',
  'Flower Queen': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480353',
  'Garmond': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480325',
  'Garmond_Zaza': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=483762',
  'Giant Centipede': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480350',
  'Giant Flea': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479122',
  'Gloom Beast': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480132',
  'Gloomfly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480133',
  'Gnat Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478975',
  'Grass Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480217',
  'Grasshopper Child': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480215',
  'Grasshopper Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480220',
  'Grasshopper Slasher': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480219',
  'Hornet Dragonfly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480223',
  'Hunter Queen': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480318',
  'Lace': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480355',
  'Last Judge': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480351',
  'Lifeblood Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479858',
  'Lightbearer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479994',
  'Lilypad Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480218',
  'Lilypad Trap': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480222',
  'Lost Lace': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480341',
  'Maggots': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480190',
  'Mite': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479681',
  'Mite Heavy': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479004',
  'Mitefly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478974',
  'MossBone Crawler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479075',
  'MossBone Crawler Fat': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480252',
  'MossBone Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479076',
  'Mossbone Mother': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480309',
  'Peaks Drifter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479036',
  'Phantom': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480356',
  'Pilgrim 01': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479551',
  'Pilgrim 01 Song': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479885',
  'Pilgrim 02': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479574',
  'Pilgrim 02 Song': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479887',
  'Pilgrim 03': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479571',
  'Pilgrim 03 Song': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479882',
  'Pilgrim 03 Understore': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479746',
  'Pilgrim 04': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479573',
  'Pilgrim 04 Song': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479886',
  'Pilgrim 05': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479755',
  'Pilgrim Bell Thrower': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478044',
  'Pilgrim Bellthrower Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478301',
  'Pilgrim Fisher': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478161',
  'Pilgrim Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479552',
  'Pilgrim Hiker': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479738',
  'Pilgrim Moss Spitter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479577',
  'Pilgrim Staff Understore': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479837',
  'Pilgrim StaffWielder': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479683',
  'Pilgrim Stomper Song': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479906',
  'Pinstress Boss': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480337',
  'Poke Swimmer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480235',
  'Pond Skater': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478159',
  'Rhino': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480193',
  'Roachfeeder Short': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478261',
  'Roachfeeder Tall': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478338',
  'Roachkeeper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478697',
  'Roachkeeper Chef': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480346',
  'Roachkeeper Chef Tiny': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478991',
  'Rock Roller': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478248',
  'Roof Crab': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478088',
  'Rosary Pilgrim': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480387',
  'Rosary Thief': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479000',
  'Sand Centipede': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480191',
  'Scholar': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479999',
  'Scrollkeeper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479991',
  'Seth': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480352',
  'Shakra': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479822',
  'Shell Fossil Mimic': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480168',
  'Shellwood Gnat': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478983',
  'Shellwood Wasp': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478160',
  'Shield Dock Worker': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479567',
  'Silk Boss': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480342',
  'Skull King': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480313',
  'Slab Fly Broodmother': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480338',
  'Slab Fly Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479011',
  'Slab Fly Mid': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479007',
  'Slab Fly Small': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479008',
  'Slab Fly Small Fresh': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480479',
  'Slab Prisoner Fly New': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479006',
  'Slab Prisoner Leaper New': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479005',
  'Small Crab': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480145',
  'Song Administrator': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480050',
  'Song Automaton 01': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479961',
  'Song Automaton 02': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479968',
  'Song Automaton Ball': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479971',
  'Song Automaton Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479938',
  'Song Automaton Fly Spike': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479963',
  'Song Automaton Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479962',
  'Song Automaton Shield': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479982',
  'Song Creeper': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480040',
  'Song Golem': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480315',
  'Song Handmaiden': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479899',
  'Song Heavy Sentry': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480052',
  'Song Knight': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480348',
  'Song Pilgrim 01': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479897',
  'Song Pilgrim 02': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480409',
  'Song Pilgrim 03': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479883',
  'Song Pilgrim Maestro': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480049',
  'Song Reed': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479880',
  'Song Reed Grand': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479918',
  'Song Scholar Acolyte': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480008',
  'Song Threaded Husk': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480036',
  'Song Threaded Husk Spin': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480043',
  'Spike Lazy Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479627',
  'Spike Swimmer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480234',
  'Spine Floater': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479570',
  'Spinner Boss': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480323',
  'Splinter Queen': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480324',
  'Stick Insect': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478980',
  'Stick Insect Charger': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478169',
  'Stick Insect Flyer': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478186',
  'Surface Scuttler': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479628',
  'Swamp Barnacle': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478962',
  'Swamp Drifter': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478738',
  'Swamp Ductsucker': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480211',
  'Swamp Goomba': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478966',
  'Swamp Mosquito': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478721',
  'Swamp Mosquito Skinny': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480261',
  'Swamp Muckman': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480206',
  'Swamp Muckman Tall': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480238',
  'Swamp Shaman': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480345',
  'Tar Slug': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479565',
  'Tar Slug Huge': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480236',
  'Tormented Trobbio': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480344',
  'Trobbio': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480343',
  'Understore Automaton': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480021',
  'Understore Automaton EX': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480022',
  'Understore Heavy': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479836',
  'Understore Mite Giant': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480005',
  'Understore Poker': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479510',
  'Understore Small': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479512',
  'Understore Thrower': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479511',
  'Vampire Gnat': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479149',
  'Void Tendrils': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479744',
  'Weaver Servitor': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478215',
  'Weaver Servitor Large': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479041',
  'White Palace Fly': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480415',
  'Wisp': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480438',
  'Wisp Pyre Effigy': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480349',
  'Wraith': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478367',
  'Zap Core Enemy': 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480336',
}

export const HUNTER_JOURNAL_TARGETS: Record<string, number> = {
  'Abyss Crawler': 16,
  'Abyss Crawler Large': 6,
  'Abyss Mass': 1,
  'Arborium Keeper': 2,
  'Aspid Collector': 15,
  'Bell Fly': 12,
  'Bell Goomba': 25,
  'Black Thread Core': 8,
  'Blade Spider': 20,
  'Blade Spider Hang': 10,
  'Bloat Roach': 12,
  'Bloom Puncher': 20,
  'Bloom Shooter': 10,
  'Blue Assistant': 1,
  'Bone Beast': 1,
  'Bone Circler': 25,
  'Bone Circler Vicious': 15,
  'Bone Crawler': 25,
  'Bone Flyer': 30,
  'Bone Flyer Giant': 2,
  'Bone Goomba': 35,
  'Bone Goomba Bounce Fly': 15,
  'Bone Goomba Large': 15,
  'Bone Hopper': 20,
  'Bone Hopper Giant': 10,
  'Bone Hunter': 15,
  'Bone Hunter Buzzer': 30,
  'Bone Hunter Chief': 6,
  'Bone Hunter Child': 20,
  'Bone Hunter Fly': 10,
  'Bone Hunter Throw': 2,
  'Bone Hunter Tiny': 25,
  'Bone Hunter Trapper': 1,
  'Bone Roller': 30,
  'Bone Spitter': 10,
  'Bone Thumper': 8,
  'Bone Worm': 10,
  'Bone Worm BlueBlood': 15,
  'Bone Worm BlueTurret': 6,
  'Centipede Trap': 30,
  'Citadel Bat': 30,
  'Citadel Bat Large': 4,
  'Clockwork Dancer': 1,
  'Clover Dancer': 1,
  'Cloverstag': 10,
  'Cloverstag White': 1,
  'Conductor Boss': 1,
  'Coral Big Jellyfish': 3,
  'Coral Brawler': 8,
  'Coral Bubble Brute': 6,
  'Coral Conch Driller': 8,
  'Coral Conch Driller Giant': 2,
  'Coral Conch Shooter': 25,
  'Coral Conch Shooter Heavy': 14,
  'Coral Conch Stabber': 16,
  'Coral Flyer': 10,
  'Coral Flyer Throw': 12,
  'Coral Goomba Large': 6,
  'Coral Goombas': 10,
  'Coral Hunter': 6,
  'Coral Judge': 15,
  'Coral Judge Child': 4,
  'Coral King': 1,
  'Coral Spike Goomba': 15,
  'Coral Swimmer Fat': 10,
  'Coral Swimmer Small': 16,
  'Coral Warrior': 10,
  'Coral Warrior Grey': 1,
  'Crawfather': 1,
  'Crow': 25,
  'Crowman': 20,
  'Crowman Dagger': 15,
  'Crowman Dagger Juror': 8,
  'Crowman Juror': 10,
  'Crowman Juror Tiny': 15,
  'Crypt Worm': 25,
  'Crystal Drifter': 10,
  'Crystal Drifter Giant': 3,
  'Dock Bomber': 10,
  'Dock Charger': 5,
  'Dock Flyer': 25,
  'Dock Guard Thrower': 1,
  'Dock Worker': 25,
  'Dragonfly Large': 10,
  'Dustroach': 20,
  'Dustroach Pollywog': 12,
  'Farmer Catcher': 20,
  'Farmer Centipede': 15,
  'Farmer Scissors': 25,
  'Farmer Wisp': 8,
  'Fields Flock Flyers': 15,
  'Fields Flyer': 20,
  'Fields Goomba': 25,
  'First Weaver': 1,
  'Flower Drifter': 25,
  'Flower Queen': 1,
  'Garmond': 1,
  'Garmond_Zaza': 1,
  'Giant Centipede': 1,
  'Giant Flea': 1,
  'Gloom Beast': 4,
  'Gloomfly': 15,
  'Gnat Giant': 10,
  'Grass Goomba': 10,
  'Grasshopper Child': 10,
  'Grasshopper Fly': 10,
  'Grasshopper Slasher': 10,
  'Hornet Dragonfly': 10,
  'Hunter Queen': 1,
  'Lace': 2,
  'Last Judge': 1,
  'Lifeblood Fly': 8,
  'Lightbearer': 20,
  'Lilypad Fly': 12,
  'Lilypad Trap': 6,
  'Lost Lace': 1,
  'Maggots': 80,
  'Mite': 30,
  'Mite Heavy': 20,
  'Mitefly': 25,
  'MossBone Crawler': 25,
  'MossBone Crawler Fat': 3,
  'MossBone Fly': 20,
  'Mossbone Mother': 3,
  'Peaks Drifter': 20,
  'Phantom': 1,
  'Pilgrim 01': 35,
  'Pilgrim 01 Song': 30,
  'Pilgrim 02': 10,
  'Pilgrim 02 Song': 15,
  'Pilgrim 03': 35,
  'Pilgrim 03 Song': 25,
  'Pilgrim 03 Understore': 20,
  'Pilgrim 04': 15,
  'Pilgrim 04 Song': 20,
  'Pilgrim 05': 5,
  'Pilgrim Bell Thrower': 10,
  'Pilgrim Bellthrower Fly': 10,
  'Pilgrim Fisher': 20,
  'Pilgrim Fly': 25,
  'Pilgrim Hiker': 10,
  'Pilgrim Moss Spitter': 20,
  'Pilgrim Staff Understore': 10,
  'Pilgrim StaffWielder': 15,
  'Pilgrim Stomper Song': 6,
  'Pinstress Boss': 1,
  'Poke Swimmer': 10,
  'Pond Skater': 15,
  'Rhino': 2,
  'Roachfeeder Short': 20,
  'Roachfeeder Tall': 20,
  'Roachkeeper': 10,
  'Roachkeeper Chef': 1,
  'Roachkeeper Chef Tiny': 10,
  'Rock Roller': 3,
  'Roof Crab': 1,
  'Rosary Pilgrim': 2,
  'Rosary Thief': 4,
  'Sand Centipede': 40,
  'Scholar': 10,
  'Scrollkeeper': 15,
  'Seth': 1,
  'Shakra': 1,
  'Shell Fossil Mimic': 3,
  'Shellwood Gnat': 15,
  'Shellwood Wasp': 12,
  'Shield Dock Worker': 10,
  'Silk Boss': 1,
  'Skull King': 1,
  'Slab Fly Broodmother': 1,
  'Slab Fly Large': 8,
  'Slab Fly Mid': 10,
  'Slab Fly Small': 15,
  'Slab Fly Small Fresh': 20,
  'Slab Prisoner Fly New': 6,
  'Slab Prisoner Leaper New': 8,
  'Small Crab': 3,
  'Song Administrator': 15,
  'Song Automaton 01': 20,
  'Song Automaton 02': 12,
  'Song Automaton Ball': 1,
  'Song Automaton Fly': 15,
  'Song Automaton Fly Spike': 10,
  'Song Automaton Goomba': 15,
  'Song Automaton Shield': 8,
  'Song Creeper': 10,
  'Song Golem': 1,
  'Song Handmaiden': 10,
  'Song Heavy Sentry': 3,
  'Song Knight': 1,
  'Song Pilgrim 01': 20,
  'Song Pilgrim 02': 3,
  'Song Pilgrim 03': 25,
  'Song Pilgrim Maestro': 6,
  'Song Reed': 30,
  'Song Reed Grand': 12,
  'Song Scholar Acolyte': 20,
  'Song Threaded Husk': 8,
  'Song Threaded Husk Spin': 8,
  'Spike Lazy Flyer': 4,
  'Spike Swimmer': 15,
  'Spine Floater': 15,
  'Spinner Boss': 1,
  'Splinter Queen': 1,
  'Stick Insect': 12,
  'Stick Insect Charger': 10,
  'Stick Insect Flyer': 10,
  'Surface Scuttler': 10,
  'Swamp Barnacle': 8,
  'Swamp Drifter': 25,
  'Swamp Ductsucker': 6,
  'Swamp Goomba': 20,
  'Swamp Mosquito': 30,
  'Swamp Mosquito Skinny': 20,
  'Swamp Muckman': 15,
  'Swamp Muckman Tall': 12,
  'Swamp Shaman': 1,
  'Tar Slug': 12,
  'Tar Slug Huge': 8,
  'Tormented Trobbio': 1,
  'Trobbio': 1,
  'Understore Automaton': 25,
  'Understore Automaton EX': 12,
  'Understore Heavy': 4,
  'Understore Mite Giant': 6,
  'Understore Poker': 25,
  'Understore Small': 15,
  'Understore Thrower': 25,
  'Vampire Gnat': 1,
  'Void Tendrils': 1,
  'Weaver Servitor': 8,
  'Weaver Servitor Large': 5,
  'White Palace Fly': 10,
  'Wisp': 15,
  'Wisp Pyre Effigy': 1,
  'Wraith': 10,
  'Zap Core Enemy': 1,
}
